### ISSUE TITLE
安装依赖出现错误

### ISSUE THREAD

**Issue by redcapcord** [Rinfair-CSP-A016/SuzunoBot-AGLAS#2]
控制台完整记录如1.txt
[1.txt](https://github.com/Rinfair-CSP-A016/SuzunoBot-AGLAS/files/11246165/1.txt)

**Comment by Rinfair** [comment]
1.txt为空，请直接把出错部分发来

**Comment by redcapcord** [comment]
WARNING: nonebot2 2.0.0rc2 does not provide the extra 'fastapi'
WARNING: nonebot2 2.0.0rc1 does not provide the extra 'fastapi'
INFO: pip is looking at multiple versions of aiosignal to determine which version is compatible with other requirements. This could take a while.
Collecting aiosignal>=1.1.2
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/76/ac/a7305707cb852b7e16ff80eaf5692309bde30e2b1100a1fcacdc8f731d97/aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
WARNING: nonebot2 2.0.0rc2 does not provide the extra 'fastapi'
WARNING: nonebot2 2.0.0rc1 does not provide the extra 'fastapi'
INFO: pip is looking at multiple versions of aiofiles to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pypiwin32 to determine which version is compatible with other requirements. This could take a while.
Collecting pypiwin32
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/2b/ca/5c086c18de8f70222787b3e824e755b68d99272531522e77bb381d4f60c8/pypiwin32-219.zip (4.8 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\不知真相的吃桃天子\AppData\Local\Temp\pip-install-5y39mj87\pypiwin32_9b8d5b2d67ef46e68c43970a55062c2e\setup.py", line 121
          print "Building pywin32", pywin32_version
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
WARNING: There was an error checking the latest version of pip.
PS C:\bot\SuzunoBot-AGLAS-master>

**Comment by Rinfair** [comment]
请更改requirements.txt最后一行为`pypiwin32==223`后重新尝试安装依赖

**Comment by Rinfair** [comment]
Closed due to no response in 20 days
