### ISSUE TITLE
不兼容python3.11

### ISSUE THREAD

**Issue by xpf580** [Rinfair-CSP-A016/SuzunoBot-AGLAS#8]
换python3.10.11的环境就安好了捏

**Comment by Rinfair** [comment]
目前暂无法继续向上兼容，请保持Python 3.10版本
请上传相关的error logs以便分析问题。

**Comment by xpf580** [comment]
安装Python包时报错：
 B:\VS\VC\Tools\MSVC\14.26.28801\bin\HostX86\x64\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IB:\Python_Project\SuzunoBot-AGLAS\TESTENV\include "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\include" "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Include" -IB:\VS\VC\Tools\MSVC\14.26.28801\ATLMFC\include -IB:\VS\VC\Tools\MSVC\14.26.28801\include "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" 
"-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcaiohttp/_websocket.c /Fobuild\temp.win-amd64-cpython-311\Release\aiohttp/_websocket.obj
      _websocket.c
      aiohttp/_websocket.c(198): fatal error C1083: 无法打开包括文件: “longintrepr.h”: No such 
file or directory
      error: command 'B:\\VS\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for aiohttp
  Building wheel for httptools (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for httptools (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [77 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\httptools
      copying httptools\_version.py -> build\lib.win-amd64-cpython-311\httptools
      copying httptools\__init__.py -> build\lib.win-amd64-cpython-311\httptools
      creating build\lib.win-amd64-cpython-311\httptools\parser
      copying httptools\parser\errors.py -> build\lib.win-amd64-cpython-311\httptools\parser   
      copying httptools\parser\__init__.py -> build\lib.win-amd64-cpython-311\httptools\parser 
      running egg_info
      writing httptools.egg-info\PKG-INFO
      writing dependency_links to httptools.egg-info\dependency_links.txt
      writing requirements to httptools.egg-info\requires.txt
      writing top-level names to httptools.egg-info\top_level.txt
      reading manifest file 'httptools.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file 'httptools.egg-info\SOURCES.txt'
      C:\Users\Xing\AppData\Local\Temp\pip-build-env-atwx3kt6\overlay\Lib\site-packages\setuptools\command\build_py.py:204: _Warning: Package 'httptools.parser' is absent from the `packages` configuration.
      !!
     
              ******************************************************************************** 
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'httptools.parser' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.
     
              This leads to an ambiguous overall configuration. If you want to distribute this 
              package, please make sure that 'httptools.parser' is explicitly added
              to the `packages` configuration field.
     
              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).
     
              You can read more about "package discovery" on setuptools documentation page:
     
              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
     
              If you don't want 'httptools.parser' to be distributed and are
              already explicitly excluding 'httptools.parser' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,      
              you can try to use `exclude_package_data`, or `include-package-data=False` in    
              combination with a more fine grained `package-data` configuration.
     
              You can read more about "package data files" on setuptools documentation page:   
     
              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html
     
     
              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ******************************************************************************** 
     
      !!
        check.warn(importable)
      copying httptools\parser\parser.c -> build\lib.win-amd64-cpython-311\httptools\parser    
      copying httptools\parser\url_parser.c -> build\lib.win-amd64-cpython-311\httptools\parser      running build_ext
      building 'httptools.parser.parser' extension
      creating build\temp.win-amd64-cpython-311
      creating build\temp.win-amd64-cpython-311\Release
      creating build\temp.win-amd64-cpython-311\Release\httptools
      creating build\temp.win-amd64-cpython-311\Release\httptools\parser
      creating build\temp.win-amd64-cpython-311\Release\vendor
      creating build\temp.win-amd64-cpython-311\Release\vendor\llhttp
      creating build\temp.win-amd64-cpython-311\Release\vendor\llhttp\src
      B:\VS\VC\Tools\MSVC\14.26.28801\bin\HostX86\x64\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\Xing\AppData\Local\Temp\pip-install-_i9ujl11\httptools_65499e4b30144d54b942c5787d8fad95\vendor\llhttp\include -IC:\Users\Xing\AppData\Local\Temp\pip-install-_i9ujl11\httptools_65499e4b30144d54b942c5787d8fad95\vendor\llhttp\src -IB:\Python_Project\SuzunoBot-AGLAS\TESTENV\include "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\include" "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.Tools\MSVC\14.26.28801\include "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tchttptools/parser/parser.c /Fobuild\temp.win-amd64-cpython-311\Release\httptools/parser/parser.obj -O2
      parser.c
      httptools/parser/parser.c(3452): warning C4090: “=”: 不同的“const”限定符
      httptools/parser/parser.c(9421): error C2037: “f_lineno”的左侧部分指定未定义的结构/联合“_frame”
      error: command 'B:\\VS\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for httptools
Failed to build aiohttp httptools
ERROR: Could not build wheels for aiohttp, httptools, which is required to install pyproject.toml-based projects
感觉可以试试包管理工具，推荐poetry，requirements.txt安装有时候会出现一些离奇的问题 OwO

**Comment by Rinfair** [comment]
尝试一下仓库里新的requirements.txt？
